# Generated by Django 4.2.11 on 2026-04-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('icon', models.CharField(default='💬', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=300)),
                ('japanese', models.CharField(max_length=300)),
                ('pronunciation_hint', models.CharField(blank=True, max_length=300)),
                ('example_context', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('audio_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='phrases.category')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=300)),
                ('definition_ja', models.CharField(max_length=300)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('idiom', 'Idiom')], default='noun', max_length=20)),
                ('example_sentence', models.CharField(max_length=500)),
                ('example_sentence_ja', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhraseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practiced_count', models.IntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrases.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phrase')},
            },
        ),
    ]
