# Generated by Django 4.2.11 on 2026-04-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('free', 'Free Conversation'), ('daily_life', 'Daily Life'), ('travel', 'Travel'), ('business', 'Business'), ('culture', 'Culture'), ('hobby', 'Hobbies')], default='free', max_length=50)),
                ('avatar_name', models.CharField(default='Emma', max_length=50)),
                ('avatar_accent', models.CharField(default='American', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('mistake_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('corrected_content', models.TextField(blank=True)),
                ('has_mistake', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
