# Generated by Django 4.2.11 on 2026-04-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=500)),
                ('corrected_text', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('mistake_type', models.CharField(choices=[('grammar', '文法'), ('vocabulary', '語彙'), ('pronunciation', '発音'), ('spelling', 'スペリング'), ('other', 'その他')], default='grammar', max_length=20)),
                ('context', models.TextField(blank=True)),
                ('is_mastered', models.BooleanField(default=False)),
                ('quiz_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='conversation.conversationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
